clear

echo "                                                                         "
echo "                                                                         "
echo "                                                                         "
echo "                                     ▄▄▄      ▓█████▄  ███▄ ▄███▓ ▄▄▄     ▄▄▄█████▓"
echo "                                    ▒████▄    ▒██▀ ██▌▓██▒▀█▀ ██▒▒████▄   ▓  ██▒ ▓▒"
echo "                                    ▒██  ▀█▄  ░██   █▌▓██    ▓██░▒██  ▀█▄ ▒ ▓██░ ▒░"
echo "                                    ░██▄▄▄▄██ ░▓█▄   ▌▒██    ▒██ ░██▄▄▄▄██░ ▓██▓ ░ "
echo "                                     ▓█   ▓██▒░▒████▓ ▒██▒   ░██▒ ▓█   ▓██▒ ▒██▒ ░ "
echo "                                     ▒▒   ▓▒█░ ▒▒▓  ▒ ░ ▒░   ░  ░ ▒▒   ▓▒█░ ▒ ░░ "
echo "                                     ▒   ▒▒ ░ ░ ▒  ▒ ░  ░      ░  ▒   ▒▒ ░   ░  "
echo "                                    ░   ▒    ░ ░  ░ ░      ░     ░   ▒    ░   "
echo "                                        ░  ░   ░           ░         ░  ░   "
echo "                                             ░     "



while :
do

  python3 /home/ubuntu/Desktop/admatv3.25/AEDAUD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AEDCAD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AEDCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AEDDKK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AEDEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AEDGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AEDINR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AEDJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AEDNOK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AEDNZD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AEDPKR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AEDSAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AEDSEK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AEDUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AEDZAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ALLGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ARSAUD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ARSBRL.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ARSCAD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ARSCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ARSEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ARSGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ARSHKD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ARSJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ARSMXN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ARSSGD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ARSUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ARSZAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AUDAED.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AUDARS.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AUDBRL.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AUDCAD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AUDCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AUDCNH.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AUDCNY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AUDCZK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AUDDKK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AUDEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AUDFJD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AUDGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AUDHKD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AUDHUF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AUDIDR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AUDILS.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AUDINR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AUDJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AUDKRW.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AUDMXN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AUDMYR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AUDNOK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AUDNZD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AUDPHP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AUDPKR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AUDPLN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AUDSEK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AUDSGD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AUDTHB.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AUDTRY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AUDTWD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AUDUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AUDZAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/AWGUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/BDTGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/BDTJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/BGNCNY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/BGNDKK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/BGNUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/BHDEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/BHDPKR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/BHDUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/BNDGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/BRLARS.py &
  python3 /home/ubuntu/Desktop/admatv3.25/BRLAUD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/BRLCAD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/BRLCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/BRLEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/BRLHKD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/BRLJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/BRLKRW.py &
  python3 /home/ubuntu/Desktop/admatv3.25/BRLMXN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/BRLSEK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/BRLSGD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/BRLUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/BRLZAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/BWPCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/BWPEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/BWPGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/BWPUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/BWPZAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CADAED.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CADARS.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CADAUD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CADBRL.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CADCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CADCNH.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CADCNY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CADDKK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CADEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CADGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CADHKD.py &
  sleep 6
  python3 /home/ubuntu/Desktop/admatv3.25/CADHKD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CADIDR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CADILS.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CADINR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CADJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CADKRW.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CADKWD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CADMXN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CADMYR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CADNOK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CADNZD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CADPKR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CADPLN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CADRUB.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CADSEK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CADSGD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CADTHB.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CADTRY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CADTWD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CADUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CADZAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CDFUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CHFAED.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CHFARS.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CHFAUD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CHFBRL.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CHFBWP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CHFCAD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CHFCNH.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CHFCNY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CHFCZK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CHFDKK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CHFEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CHFGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CHFHKD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CHFHUF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CHFIDR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CHFILS.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CHFINR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CHFJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CHFKRW.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CHFMXN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CHFMYR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CHFNOK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CHFNZD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CHFPKR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CHFPLN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CHFRON.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CHFRUB.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CHFSEK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CHFSGD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CHFSZL.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CHFTHB.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CHFTRY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CHFTWD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CHFUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CHFZAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CLPEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CLPGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CLPUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CNHHKD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CNHIDR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CNHINR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CNHJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CNHKRW.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CNHPHP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CNHTHB.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CNHTWD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CNYAUD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CNYBGN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CNYCAD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CNYCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CNYDKK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CNYEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CNYGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CNYHKD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CNYJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CNYKRW.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CNYMYR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CNYNZD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CNYUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CNYZAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/COPDKK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CRCGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CYPZAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CZKCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CZKDKK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CZKEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CZKJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CZKMXN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CZKNOK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CZKPLN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CZKSEK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/CZKUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/DJFGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/DKKAED.py &
  python3 /home/ubuntu/Desktop/admatv3.25/DKKAUD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/DKKBGN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/DKKBRL.py &
  python3 /home/ubuntu/Desktop/admatv3.25/DKKCAD.py &
  sleep 6
  python3 /home/ubuntu/Desktop/admatv3.25/DKKCAD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/DKKCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/DKKCNY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/DKKCOP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/DKKCZK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/DKKEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/DKKGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/DKKHKD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/DKKHUF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/DKKINR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/DKKISK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/DKKJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/DKKMXN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/DKKMYR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/DKKNOK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/DKKNZD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/DKKPHP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/DKKPKR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/DKKPLN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/DKKSEK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/DKKSGD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/DKKTHB.py &
  python3 /home/ubuntu/Desktop/admatv3.25/DKKTRY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/DKKTWD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/DKKUAH.py &
  python3 /home/ubuntu/Desktop/admatv3.25/DKKUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/DKKZAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/DOPGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/DZDEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/DZDUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EGPEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EGPJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EGPPKR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EGPUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ETBGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURAED.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURAFN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURALL.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURAMD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURARS.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURAUD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURBBD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURBDT.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURBGN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURBHD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURBIF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURBND.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURBOB.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURBRL.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURBSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURBWP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURBZD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURCAD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURCLP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURCNH.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURCNY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURCOP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURCRC.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURCUP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURCZK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURDJF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURDKK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURDOP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURDZD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EUREGP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURETB.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURFJD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURGHS.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURGMD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURGNF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURGTQ.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURHKD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURHNL.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURHRK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURHTG.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURHUF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURIDR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURILS.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURINR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURIQD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURISK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURJMD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURJOD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURKES.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURKHR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURKRW.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURKWD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURKYD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURKZT.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURLAK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURLBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURLKR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURLSL.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURLYD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURMAD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURMDL.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURMKD.py &
  sleep 6
  python3 /home/ubuntu/Desktop/admatv3.25/EURMKD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURMMK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURMOP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURMUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURMVR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURMWK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURMXN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURMYR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURNAD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURNGN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURNIO.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURNOK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURNPR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURNZD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EUROMR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURPAB.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURPEN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURPGK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURPHP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURPKR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURPLN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURPYG.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURQAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURRON.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURRSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURRUB.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURRWF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURSAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURSEK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURSGD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURSOS.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURSVC.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURSZL.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURTHB.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURTND.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURTRY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURTTD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURTWD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURTZS.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURUAH.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURUGX.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURUYU.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURUZS.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURVND.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURYER.py &
  python3 /home/ubuntu/Desktop/admatv3.25/EURZAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/FJDGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/FJDUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPAED.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPALL.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPARS.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPAUD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPBDT.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPBGN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPBHD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPBIF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPBMD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPBND.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPBRL.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPBWP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPCAD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPCLP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPCNH.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPCNY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPCOP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPCRC.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPCZK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPDJF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPDKK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPDOP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPDZD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPEGP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPETB.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPFJD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPGTQ.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPHKD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPHNL.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPHRK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPHTG.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPHUF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPIDR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPILS.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPINR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPIQD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPISK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPJMD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPJOD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPKES.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPKRW.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPKWD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPKZT.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPLBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPLKR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPMAD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPMUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPMVR.py &
  sleep 6
  python3 /home/ubuntu/Desktop/admatv3.25/GBPMVR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPMWK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPMXN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPMYR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPNGN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPNIO.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPNOK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPNZD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPOMR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPPEN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPPGK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPPHP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPPKR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPPLN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPQAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPRON.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPRSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPRUB.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPSAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPSCR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPSEK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPSGD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPSZL.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPTHB.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPTND.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPTRY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPTTD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPTWD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPUAH.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPUGX.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPVND.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPXAF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPXCD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPXPF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GBPZAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GHSEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GHSUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/GTQGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/HKDARS.py &
  python3 /home/ubuntu/Desktop/admatv3.25/HKDAUD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/HKDBRL.py &
  python3 /home/ubuntu/Desktop/admatv3.25/HKDCAD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/HKDCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/HKDCNY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/HKDDKK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/HKDEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/HKDGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/HKDIDR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/HKDINR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/HKDJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/HKDKRW.py &
  python3 /home/ubuntu/Desktop/admatv3.25/HKDMXN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/HKDMYR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/HKDNZD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/HKDPKR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/HKDPLN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/HKDSEK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/HKDSGD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/HKDTHB.py &
  python3 /home/ubuntu/Desktop/admatv3.25/HKDTWD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/HKDUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/HKDZAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/HNLGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/HRKEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/HRKPLN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/HRKUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/HTGGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/HUFCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/HUFDKK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/HUFEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/HUFPLN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/HUFUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/IDRAUD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/IDRCAD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/IDRCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/IDRCNY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/IDREUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/IDRGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/IDRHKD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/IDRINR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/IDRJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/IDRKRW.py &
  python3 /home/ubuntu/Desktop/admatv3.25/IDRMYR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/IDRNZD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/IDRSGD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/IDRTHB.py &
  python3 /home/ubuntu/Desktop/admatv3.25/IDRTWD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/IDRUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/IDRZAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ILSAUD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ILSCAD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ILSCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ILSJOD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ILSJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ILSPLN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ILSSEK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ILSUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/INRAUD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/INRCAD.py &
  sleep 6
  python3 /home/ubuntu/Desktop/admatv3.25/INRCAD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/INRCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/INRCNY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/INREUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/INRGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/INRHKD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/INRJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/INRKRW.py &
  python3 /home/ubuntu/Desktop/admatv3.25/INRMYR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/INRNZD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/INRPKR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/INRSEK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/INRTHB.py &
  python3 /home/ubuntu/Desktop/admatv3.25/INRTWD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/INRUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/INRZAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/IQDGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ISKCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ISKDKK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ISKGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/JMDGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/JODAED.py &
  python3 /home/ubuntu/Desktop/admatv3.25/JODEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/JODILS.py &
  python3 /home/ubuntu/Desktop/admatv3.25/JODUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/JPYAED.py &
  python3 /home/ubuntu/Desktop/admatv3.25/JPYARS.py &
  python3 /home/ubuntu/Desktop/admatv3.25/JPYAUD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/JPYBRL.py &
  python3 /home/ubuntu/Desktop/admatv3.25/JPYCAD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/JPYCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/JPYCLP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/JPYCNY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/JPYCZK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/JPYDKK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/JPYEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/JPYGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/JPYHKD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/JPYIDR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/JPYILS.py &
  python3 /home/ubuntu/Desktop/admatv3.25/JPYINR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/JPYKRW.py &
  python3 /home/ubuntu/Desktop/admatv3.25/JPYMXN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/JPYMYR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/JPYNOK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/JPYNZD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/JPYPKR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/JPYPLN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/JPYRUB.py &
  python3 /home/ubuntu/Desktop/admatv3.25/JPYSEK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/JPYTHB.py &
  python3 /home/ubuntu/Desktop/admatv3.25/JPYTWD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/JPYUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/JPYZAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/KESUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/KESZAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/KMFUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/KRWAUD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/KRWBRL.py &
  python3 /home/ubuntu/Desktop/admatv3.25/KRWCAD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/KRWCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/KRWCNY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/KRWEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/KRWHKD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/KRWIDR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/KRWINR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/KRWJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/KRWMYR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/KRWNZD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/KRWRUB.py &
  python3 /home/ubuntu/Desktop/admatv3.25/KRWSEK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/KRWSGD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/KRWTHB.py &
  python3 /home/ubuntu/Desktop/admatv3.25/KRWTWD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/KRWUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/KRWZAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/KWDAED.py &
  python3 /home/ubuntu/Desktop/admatv3.25/KWDGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/KWDPKR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/KWDUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/KZTGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/LBPUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/LKRUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/LRDUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MADGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MADUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MDLEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MDLUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MKDUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MUREUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MURGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MURUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MURZAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MVRUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MWKGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MXNARS.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MXNAUD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MXNBRL.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MXNCAD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MXNCHF.py &
  sleep 6
  python3 /home/ubuntu/Desktop/admatv3.25/MXNCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MXNCZK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MXNDKK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MXNEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MXNGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MXNHKD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MXNJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MXNSGD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MXNUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MXNZAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MYRAUD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MYRCAD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MYRCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MYRCNH.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MYRCNY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MYRDKK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MYREUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MYRGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MYRHKD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MYRIDR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MYRINR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MYRJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MYRKRW.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MYRNZD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MYRPKR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MYRSGD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MYRTHB.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MYRTWD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MYRUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/MYRZAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NGNGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NGNJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NIOGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NOKCAD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NOKCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NOKCNH.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NOKDKK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NOKEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NOKGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NOKINR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NOKJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NOKPLN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NOKSEK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NOKUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NOKZAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NZDAED.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NZDAUD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NZDCAD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NZDCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NZDCNH.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NZDCNY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NZDCZK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NZDDKK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NZDEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NZDGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NZDHKD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NZDHUF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NZDIDR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NZDINR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NZDJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NZDKRW.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NZDMXN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NZDMYR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NZDNOK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NZDPKR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NZDPLN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NZDSEK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NZDSGD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NZDTHB.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NZDTRY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NZDTWD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NZDUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/NZDZAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/OMRAED.py &
  python3 /home/ubuntu/Desktop/admatv3.25/OMRGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/OMRPKR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/OMRUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/OMRZAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/PENGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/PGKGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/PHPDKK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/PHPGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/PHPJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/PHPUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/PKRGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/PKRJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/PKRZAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/PLNCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/PLNCZK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/PLNDKK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/PLNEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/PLNGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/PLNHUF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/PLNILS.py &
  python3 /home/ubuntu/Desktop/admatv3.25/PLNJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/PLNNOK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/PLNSEK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/PLNUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/QARAED.py &
  python3 /home/ubuntu/Desktop/admatv3.25/QARGBP.py &
  sleep 6
  python3 /home/ubuntu/Desktop/admatv3.25/QARGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/QARPKR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/QARUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/QARZAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/RONCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/RONGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/RONUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/RSDUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/RUBCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/RUBGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/RUBJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/RUBKRW.py &
  python3 /home/ubuntu/Desktop/admatv3.25/RUBPLN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/RUBUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SAREUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SARPKR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SARUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SCRGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SCRUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SEKAUD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SEKCAD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SEKCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SEKCNH.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SEKCZK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SEKDKK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SEKEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SEKGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SEKILS.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SEKINR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SEKJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SEKNOK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SEKPLN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SEKUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SEKZAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SGDAED.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SGDARS.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SGDAUD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SGDBRL.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SGDCAD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SGDCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SGDCNH.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SGDCNY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SGDDKK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SGDEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SGDGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SGDHKD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SGDIDR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SGDINR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SGDJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SGDKRW.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SGDMXN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SGDMYR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SGDNZD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SGDPKR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SGDPLN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SGDSEK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SGDTHB.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SGDTWD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SGDUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SGDZAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SHPUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SLLUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SZLCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SZLEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SZLGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/SZLUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/THBAUD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/THBCAD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/THBCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/THBCNY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/THBEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/THBGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/THBHKD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/THBIDR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/THBINR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/THBJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/THBKRW.py &
  python3 /home/ubuntu/Desktop/admatv3.25/THBMYR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/THBNZD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/THBPKR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/THBSGD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/THBTWD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/THBUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/THBZAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/TNDGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/TNDUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/TRYCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/TRYDKK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/TRYJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/TRYPLN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/TRYUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/TRYZAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/TTDGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/TWDAUD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/TWDCAD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/TWDCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/TWDCNY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/TWDDKK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/TWDHKD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/TWDIDR.py &
  sleep 6
  python3 /home/ubuntu/Desktop/admatv3.25/TWDIDR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/TWDINR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/TWDJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/TWDKRW.py &
  python3 /home/ubuntu/Desktop/admatv3.25/TWDMYR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/TWDNZD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/TWDPKR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/TWDSEK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/TWDSGD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/TWDTHB.py &
  python3 /home/ubuntu/Desktop/admatv3.25/TWDUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/TWDZAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/TZSZAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/UAHDKK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/UAHEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/UAHUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDAED.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDAFN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDALL.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDAMD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDARS.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDAUD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDAWG.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDBDT.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDBGN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDBHD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDBIF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDBND.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDBOB.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDBRL.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDBWP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDBZD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDCAD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDCDF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDCLP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDCNH.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDCNY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDCOP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDCRC.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDCUP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDCVE.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDCZK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDDJF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDDKK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDDOP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDDZD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDEGP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDETB.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDFJD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDGEL.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDGHS.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDGMD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDGNF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDGTQ.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDHKD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDHNL.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDHRK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDHTG.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDHUF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDIDR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDILS.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDINR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDIQD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDIRR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDISK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDJOD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDKES.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDKHR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDKMF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDKRW.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDKWD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDKZT.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDLAK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDLBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDLKR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDLRD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDLSL.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDLYD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDMAD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDMDL.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDMKD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDMMK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDMOP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDMUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDMVR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDMWK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDMXN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDMYR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDNAD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDNGN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDNIO.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDNOK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDNPR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDNZD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDOMR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDPAB.py &
  sleep 6
  python3 /home/ubuntu/Desktop/admatv3.25/USDPAB.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDPEN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDPGK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDPHP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDPKR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDPLN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDPYG.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDQAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDRON.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDRSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDRUB.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDRWF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDSAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDSCR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDSEK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDSGD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDSLL.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDSOS.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDSVC.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDSZL.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDTHB.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDTND.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDTRY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDTWD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDTZS.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDUAH.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDUYU.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDUZS.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDVND.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDXAF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDXOF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDXPF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDYER.py &
  python3 /home/ubuntu/Desktop/admatv3.25/USDZAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/UYUEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/UYUUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/VNDJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/VNDXAF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAGARS.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAGAUD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAGBRL.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAGCAD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAGCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAGCNY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAGEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAGGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAGHKD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAGINR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAGJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAGKRW.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAGMXN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAGRUB.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAGSAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAGTRY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAGUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAGZAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAUARS.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAUAUD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAUBRL.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAUCAD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAUCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAUCNY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAUEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAUGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAUHKD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAUINR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAUJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAUMXN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAURUB.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAUSAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAUTHB.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAUTRY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAUUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XAUZAR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XCDGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XPDEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XPDGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XPDUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XPFGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XPTEUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XPTGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/XPTUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/YERUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ZARAED.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ZARARS.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ZARAUD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ZARBRL.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ZARBWP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ZARCAD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ZARCHF.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ZARCNY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ZARCYP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ZARDKK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ZAREUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ZARGBP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ZARHKD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ZARIDR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ZARINR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ZARJPY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ZARKES.py &
  sleep 6
  python3 /home/ubuntu/Desktop/admatv3.25/ZARKES.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ZARKRW.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ZARMUR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ZARMXN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ZARMYR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ZARNOK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ZARNZD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ZAROMR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ZARPHP.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ZARPKR.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ZARPLN.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ZARSEK.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ZARSGD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ZARTHB.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ZARTRY.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ZARTWD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/ZARUSD.py &
  python3 /home/ubuntu/Desktop/admatv3.25/%launcher%

done
